/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDACCESSRIGHT } from "./CDACCESSRIGHT"
import { HcpartyType } from "./HcpartyType"
import { TransactionIdType } from "./TransactionIdType"

export class AccessRightType {
  constructor(json: JSON | any) {
    Object.assign(this as AccessRightType, json)
  }

  cd?: CDACCESSRIGHT
  hcparty?: HcpartyType
  transaction?: TransactionIdType
}
