/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class AgreementTransaction {
  constructor(json: JSON | any) {
    Object.assign(this as AgreementTransaction, json)
  }

  accepted?: boolean
  careProviderReference?: string
  content?: Array<string>
  coverageType?: string
  decisionReference?: string
  end?: number
  inTreatment?: boolean
  ioRequestReference?: string
  paragraph?: string
  quantityUnit?: string
  quantityValue?: number
  refusalJustification?: { [key: string]: string }
  responseType?: string
  restStrength?: number
  restStrengthUnit?: string
  restUnitNumber?: number
  start?: number
  strength?: number
  strengthUnit?: string
  timestamp?: number
  unitNumber?: number
}
