/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { WhereType } from "./WhereType"

import { decodeBase64 } from "./ModelHelper"

export class BirthDeceaseType {
  constructor(json: JSON | any) {
    Object.assign(this as BirthDeceaseType, json)
  }

  date?: string
  localisation?: WhereType
  modificationDate?: string
  origin?: BirthDeceaseType.OriginEnum
}
export namespace BirthDeceaseType {
  export type OriginEnum = "BCSS_KSZ" | "RN_RR"
  export const OriginEnum = {
    BCSSKSZ: "BCSS_KSZ" as OriginEnum,
    RNRR: "RN_RR" as OriginEnum
  }
}
