/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { FaultType } from "./FaultType"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

import { decodeBase64 } from "./ModelHelper"

export class CancelSubscriptionResultWithResponse {
  constructor(json: JSON | any) {
    Object.assign(
      this as CancelSubscriptionResultWithResponse,
      json,
      json.kmehrMessage ? { kmehrMessage: decodeBase64(json.kmehrMessage) } : {},
      json.xades ? { xades: decodeBase64(json.xades) } : {}
    )
  }

  commonOutput?: CommonOutput
  decisionReference?: string
  errors?: Array<MycarenetError>
  genericErrors?: Array<FaultType>
  kmehrMessage?: ArrayBuffer
  mycarenetConversation?: MycarenetConversation
  subscriptionsCancelDate?: number
  xades?: ArrayBuffer
}
