/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressDeclarationType } from "./AddressDeclarationType"
import { BirthInfoDeclarationType } from "./BirthInfoDeclarationType"
import { CivilStatesDeclarationType } from "./CivilStatesDeclarationType"
import { ContactAddressDeclarationType } from "./ContactAddressDeclarationType"
import { DeceaseInfoDeclarationType } from "./DeceaseInfoDeclarationType"
import { GenderInfoDeclarationType } from "./GenderInfoDeclarationType"
import { NameInfoDeclarationType } from "./NameInfoDeclarationType"
import { NationalitiesDeclarationType } from "./NationalitiesDeclarationType"

import { decodeBase64 } from "./ModelHelper"

export class CbssPersonRequestType {
  constructor(json: JSON | any) {
    Object.assign(this as CbssPersonRequestType, json)
  }

  address?: AddressDeclarationType
  birth?: BirthInfoDeclarationType
  civilStates?: CivilStatesDeclarationType
  contactAddress?: ContactAddressDeclarationType
  decease?: DeceaseInfoDeclarationType
  gender?: GenderInfoDeclarationType
  name?: NameInfoDeclarationType
  nationalities?: NationalitiesDeclarationType
}
