/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InformationType } from "./InformationType"

import { decodeBase64 } from "./ModelHelper"

export class CbssStatusType {
  constructor(json: JSON | any) {
    Object.assign(this as CbssStatusType, json)
  }

  code?: string
  description?: string
  information?: Array<InformationType>
  value?: string
}
