/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDCERTAINTY {
  constructor(json: JSON | any) {
    Object.assign(this as CDCERTAINTY, json)
  }

  dn?: string
  l?: string
  s?: string
  sv?: string
  value?: CDCERTAINTY.ValueEnum
}
export namespace CDCERTAINTY {
  export type ValueEnum = "EXCLUDED" | "PROBABLE" | "PROVEN" | "UNPROBABLE" | "UNDEFINED"
  export const ValueEnum = {
    EXCLUDED: "EXCLUDED" as ValueEnum,
    PROBABLE: "PROBABLE" as ValueEnum,
    PROVEN: "PROVEN" as ValueEnum,
    UNPROBABLE: "UNPROBABLE" as ValueEnum,
    UNDEFINED: "UNDEFINED" as ValueEnum
  }
}
