/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDDAYPERIOD {
  constructor(json: JSON | any) {
    Object.assign(this as CDDAYPERIOD, json)
  }

  dn?: string
  l?: string
  s?: string
  sv?: string
  value?: CDDAYPERIOD.ValueEnum
}
export namespace CDDAYPERIOD {
  export type ValueEnum =
    | "AFTERBREAKFAST"
    | "AFTERDINNER"
    | "AFTERLUNCH"
    | "AFTERMEAL"
    | "AFTERNOON"
    | "BEFOREBREAKFAST"
    | "BEFOREDINNER"
    | "BEFORELUNCH"
    | "BETWEENBREAKFASTANDLUNCH"
    | "BETWEENDINNERANDSLEEP"
    | "BETWEENLUNCHANDDINNER"
    | "BETWEENMEALS"
    | "EVENING"
    | "MORNING"
    | "NIGHT"
    | "THEHOUROFSLEEP"
    | "DURINGBREAKFAST"
    | "DURINGLUNCH"
    | "DURINGDINNER"
  export const ValueEnum = {
    AFTERBREAKFAST: "AFTERBREAKFAST" as ValueEnum,
    AFTERDINNER: "AFTERDINNER" as ValueEnum,
    AFTERLUNCH: "AFTERLUNCH" as ValueEnum,
    AFTERMEAL: "AFTERMEAL" as ValueEnum,
    AFTERNOON: "AFTERNOON" as ValueEnum,
    BEFOREBREAKFAST: "BEFOREBREAKFAST" as ValueEnum,
    BEFOREDINNER: "BEFOREDINNER" as ValueEnum,
    BEFORELUNCH: "BEFORELUNCH" as ValueEnum,
    BETWEENBREAKFASTANDLUNCH: "BETWEENBREAKFASTANDLUNCH" as ValueEnum,
    BETWEENDINNERANDSLEEP: "BETWEENDINNERANDSLEEP" as ValueEnum,
    BETWEENLUNCHANDDINNER: "BETWEENLUNCHANDDINNER" as ValueEnum,
    BETWEENMEALS: "BETWEENMEALS" as ValueEnum,
    EVENING: "EVENING" as ValueEnum,
    MORNING: "MORNING" as ValueEnum,
    NIGHT: "NIGHT" as ValueEnum,
    THEHOUROFSLEEP: "THEHOUROFSLEEP" as ValueEnum,
    DURINGBREAKFAST: "DURINGBREAKFAST" as ValueEnum,
    DURINGLUNCH: "DURINGLUNCH" as ValueEnum,
    DURINGDINNER: "DURINGDINNER" as ValueEnum
  }
}
