/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class CDENCRYPTIONMETHOD {
  constructor(json: JSON | any) {
    Object.assign(this as CDENCRYPTIONMETHOD, json)
  }

  dn?: string
  l?: string
  s?: CDENCRYPTIONMETHOD.SEnum
  sv?: string
  value?: CDENCRYPTIONMETHOD.ValueEnum
}
export namespace CDENCRYPTIONMETHOD {
  export type SEnum = "CD_ENCRYPTION_METHOD"
  export const SEnum = {
    METHOD: "CD_ENCRYPTION_METHOD" as SEnum
  }
  export type ValueEnum = "CMS"
  export const ValueEnum = {
    CMS: "CMS" as ValueEnum
  }
}
