/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class CDEXTERNALSOURCE {
  constructor(json: JSON | any) {
    Object.assign(this as CDEXTERNALSOURCE, json)
  }

  dn?: string
  l?: string
  s?: CDEXTERNALSOURCE.SEnum
  sl?: string
  sv?: string
  value?: string
}
export namespace CDEXTERNALSOURCE {
  export type SEnum = "CD_EXTERNALSOURCE" | "LOCAL"
  export const SEnum = {
    CDEXTERNALSOURCE: "CD_EXTERNALSOURCE" as SEnum,
    LOCAL: "LOCAL" as SEnum
  }
}
