/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDFORMULARY {
  constructor(json: JSON | any) {
    Object.assign(this as CDFORMULARY, json)
  }

  dn?: string
  l?: string
  s?: CDFORMULARY.SEnum
  sv?: string
  value?: string
}
export namespace CDFORMULARY {
  export type SEnum = "CD_FORMULARY" | "CD_FORMULARYREFERENCE"
  export const SEnum = {
    FORMULARY: "CD_FORMULARY" as SEnum,
    FORMULARYREFERENCE: "CD_FORMULARYREFERENCE" as SEnum
  }
}
