/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDMESSAGE {
  constructor(json: JSON | any) {
    Object.assign(this as CDMESSAGE, json)
  }

  dn?: string
  l?: string
  s?: string
  sv?: string
  value?: CDMESSAGE.ValueEnum
}
export namespace CDMESSAGE {
  export type ValueEnum =
    | "GPSOFTWAREMIGRATION"
    | "GPPATIENTMIGRATION"
    | "PTSOFTWAREMIGRATION"
    | "PTPATIENTMIGRATION"
    | "NURSINGSOFTWAREMIGRATION"
    | "NURSINGPATIENTMIGRATION"
  export const ValueEnum = {
    GPSOFTWAREMIGRATION: "GPSOFTWAREMIGRATION" as ValueEnum,
    GPPATIENTMIGRATION: "GPPATIENTMIGRATION" as ValueEnum,
    PTSOFTWAREMIGRATION: "PTSOFTWAREMIGRATION" as ValueEnum,
    PTPATIENTMIGRATION: "PTPATIENTMIGRATION" as ValueEnum,
    NURSINGSOFTWAREMIGRATION: "NURSINGSOFTWAREMIGRATION" as ValueEnum,
    NURSINGPATIENTMIGRATION: "NURSINGPATIENTMIGRATION" as ValueEnum
  }
}
