/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDMEDICATION {
  constructor(json: JSON | any) {
    Object.assign(this as CDMEDICATION, json)
  }

  dn?: string
  l?: string
  s?: CDMEDICATION.SEnum
  sl?: string
  sv?: string
  value?: string
}
export namespace CDMEDICATION {
  export type SEnum = "CD_DRUG_CNK" | "CD_VACCINE" | "LOCAL"
  export const SEnum = {
    CDDRUGCNK: "CD_DRUG_CNK" as SEnum,
    CDVACCINE: "CD_VACCINE" as SEnum,
    LOCAL: "LOCAL" as SEnum
  }
}
