/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDSEX {
  constructor(json: JSON | any) {
    Object.assign(this as CDSEX, json)
  }

  dn?: string
  l?: string
  s?: string
  sv?: string
  value?: CDSEX.ValueEnum
}
export namespace CDSEX {
  export type ValueEnum = "CHANGED" | "FEMALE" | "MALE" | "UNKNOWN" | "UNDEFINED"
  export const ValueEnum = {
    CHANGED: "CHANGED" as ValueEnum,
    FEMALE: "FEMALE" as ValueEnum,
    MALE: "MALE" as ValueEnum,
    UNKNOWN: "UNKNOWN" as ValueEnum,
    UNDEFINED: "UNDEFINED" as ValueEnum
  }
}
