/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDSITE {
  constructor(json: JSON | any) {
    Object.assign(this as CDSITE, json)
  }

  dn?: string
  l?: string
  s?: CDSITE.SEnum
  sv?: string
  value?: string
}
export namespace CDSITE {
  export type SEnum = "CD_SITE" | "CD_DEFIB_SITE"
  export const SEnum = {
    SITE: "CD_SITE" as SEnum,
    DEFIBSITE: "CD_DEFIB_SITE" as SEnum
  }
}
