/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDTEMPORALITY {
  constructor(json: JSON | any) {
    Object.assign(this as CDTEMPORALITY, json)
  }

  dn?: string
  l?: string
  s?: string
  sv?: string
  value?: CDTEMPORALITY.ValueEnum
}
export namespace CDTEMPORALITY {
  export type ValueEnum =
    | "ONESHOT"
    | "ACUTE"
    | "CHRONIC"
    | "REACTIVATION"
    | "REMISSION"
    | "SUBACUTE"
  export const ValueEnum = {
    ONESHOT: "ONESHOT" as ValueEnum,
    ACUTE: "ACUTE" as ValueEnum,
    CHRONIC: "CHRONIC" as ValueEnum,
    REACTIVATION: "REACTIVATION" as ValueEnum,
    REMISSION: "REMISSION" as ValueEnum,
    SUBACUTE: "SUBACUTE" as ValueEnum
  }
}
