/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class CDTIMEUNIT {
  constructor(json: JSON | any) {
    Object.assign(this as CDTIMEUNIT, json)
  }

  dn?: string
  l?: string
  s?: CDTIMEUNIT.SEnum
  sl?: string
  sv?: string
  value?: string
}
export namespace CDTIMEUNIT {
  export type SEnum = "CD_TIMEUNIT" | "LOCAL"
  export const SEnum = {
    CDTIMEUNIT: "CD_TIMEUNIT" as SEnum,
    LOCAL: "LOCAL" as SEnum
  }
}
