/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NameType } from "./NameType"
import { PartnerType } from "./PartnerType"
import { WhereResponseType } from "./WhereResponseType"

export class CivilStateResponseType {
  constructor(json: JSON | any) {
    Object.assign(this as CivilStateResponseType, json)
  }

  civilStateCode?: string
  civilStateDescriptions?: Array<NameType>
  endDate?: Date
  location?: WhereResponseType
  partner?: PartnerType
  startDate?: Date
}
