/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { JudgmentType } from "./JudgmentType"
import { LocalizedDescriptionType } from "./LocalizedDescriptionType"
import { LocationType } from "./LocationType"
import { PartnerType } from "./PartnerType"
import { TranscriptionType } from "./TranscriptionType"

import { decodeBase64 } from "./ModelHelper"

export class CivilStateInfoBaseType {
  constructor(json: JSON | any) {
    Object.assign(this as CivilStateInfoBaseType, json)
  }

  civilStateCode?: number
  civilStateDescriptions?: Array<LocalizedDescriptionType>
  inceptionDate?: Date
  judgment?: JudgmentType
  location?: LocationType
  partner?: PartnerType
  transcription?: TranscriptionType
}
