/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { InhabitantType } from "./InhabitantType"
import { LocalisedString } from "./LocalisedString"
import { WhereType } from "./WhereType"

export class CivilStateType {
  constructor(json: JSON | any) {
    Object.assign(this as CivilStateType, json)
  }

  code?: number
  descriptions?: Array<LocalisedString>
  localisation?: WhereType
  modificationDate?: string
  origin?: CivilStateType.OriginEnum
  partner?: InhabitantType
}
export namespace CivilStateType {
  export type OriginEnum = "BCSS_KSZ" | "RN_RR"
  export const OriginEnum = {
    BCSSKSZ: "BCSS_KSZ" as OriginEnum,
    RNRR: "RN_RR" as OriginEnum
  }
}
