/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BirthDeceaseType } from "./BirthDeceaseType"
import { CivilStateType } from "./CivilStateType"
import { ConsultRnAddressDto } from "./ConsultRnAddressDto"
import { GenderType } from "./GenderType"
import { NameType } from "./NameType"
import { NationalityType } from "./NationalityType"

export class ConsultRnPersonDataDto {
  constructor(json: JSON | any) {
    Object.assign(this as ConsultRnPersonDataDto, json)
  }

  address?: ConsultRnAddressDto
  birth?: BirthDeceaseType
  civilstate?: CivilStateType
  decease?: BirthDeceaseType
  gender?: GenderType
  name?: NameType
  nationality?: NationalityType
}
