/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ConsultRnPersonDataDto } from "./ConsultRnPersonDataDto"
import { EncodedSSINType } from "./EncodedSSINType"

export class ConsultRnPersonDto {
  constructor(json: JSON | any) {
    Object.assign(this as ConsultRnPersonDto, json)
  }

  modificationDate?: string
  origin?: ConsultRnPersonDto.OriginEnum
  personData?: ConsultRnPersonDataDto
  ssin?: EncodedSSINType
}
export namespace ConsultRnPersonDto {
  export type OriginEnum = "BCSS_KSZ" | "RN_RR"
  export const OriginEnum = {
    BCSSKSZ: "BCSS_KSZ" as OriginEnum,
    RNRR: "RN_RR" as OriginEnum
  }
}
