/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SsinStatusType } from "./SsinStatusType"
import { Status } from "./Status"

import { decodeBase64 } from "./ModelHelper"

export class ConsultCurrentSsinResponse {
  constructor(json: JSON | any) {
    Object.assign(this as ConsultCurrentSsinResponse, json)
  }

  id?: string
  inResponseTo?: string
  issueInstant?: Date
  ssin?: SsinStatusType
  status?: Status
}
