/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDCONTENT } from "./CDCONTENT"
import { CompoundprescriptionType } from "./CompoundprescriptionType"
import { ErrorType } from "./ErrorType"
import { HcpartyType } from "./HcpartyType"
import { HolterType } from "./HolterType"
import { IDKMEHR } from "./IDKMEHR"
import { IncapacityType } from "./IncapacityType"
import { InsuranceType } from "./InsuranceType"
import { LnkType } from "./LnkType"
import { LocationBirthPlaceType } from "./LocationBirthPlaceType"
import { MaxrefType } from "./MaxrefType"
import { MedicationType } from "./MedicationType"
import { MedicinalProductType } from "./MedicinalProductType"
import { MinrefType } from "./MinrefType"
import { PersonType } from "./PersonType"
import { RefscopeType } from "./RefscopeType"
import { Substanceproduct } from "./Substanceproduct"
import { TextType } from "./TextType"
import { UnitType } from "./UnitType"
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

import { decodeBase64 } from "./ModelHelper"

export class ContentType {
  constructor(json: JSON | any) {
    Object.assign(this as ContentType, json)
  }

  bacteriology?: TextType
  _boolean?: boolean
  cds?: Array<CDCONTENT>
  compoundprescription?: CompoundprescriptionType
  date?: Date
  decimal?: number
  ecg?: TextType
  error?: ErrorType
  hcparty?: HcpartyType
  holter?: HolterType
  ids?: Array<IDKMEHR>
  incapacity?: IncapacityType
  insurance?: InsuranceType
  lnks?: Array<LnkType>
  location?: LocationBirthPlaceType
  maxref?: MaxrefType
  medication?: MedicationType
  medicinalproduct?: MedicinalProductType
  minref?: MinrefType
  person?: PersonType
  refscopes?: Array<RefscopeType>
  substanceproduct?: Substanceproduct
  texts?: Array<TextType>
  time?: Date
  unit?: UnitType
  unsignedInt?: number
  year?: XMLGregorianCalendar
  yearmonth?: XMLGregorianCalendar
}
