/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class ContactAddress {
  constructor(json: JSON | any) {
    Object.assign(this as ContactAddress, json)
  }

  countryCode?: number
  countryIsoCode?: string
  cityCode?: string
  countryName?: string
  cityName?: string
  postalCode?: string
  streetName?: string
  typeCode?: number
}
