/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDCONTENT } from "./CDCONTENT"
import { HcpartyType } from "./HcpartyType"
import { IDKMEHR } from "./IDKMEHR"
import { PersonType } from "./PersonType"
import { TextType } from "./TextType"
import { UnitType } from "./UnitType"

export class ContentlocalitemattributeType {
  constructor(json: JSON | any) {
    Object.assign(this as ContentlocalitemattributeType, json)
  }

  _boolean?: boolean
  cds?: Array<CDCONTENT>
  date?: Date
  decimal?: number
  hcparty?: HcpartyType
  ids?: Array<IDKMEHR>
  lnks?: Array<any>
  person?: PersonType
  text?: TextType
  time?: Date
  unit?: UnitType
}
