/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { LocalizedDescriptionType } from "./LocalizedDescriptionType"

import { decodeBase64 } from "./ModelHelper"

export class DiplomaticPostType {
  constructor(json: JSON | any) {
    Object.assign(this as DiplomaticPostType, json)
  }

  countryCode?: number
  countryIsoCode?: string
  countryNames?: Array<LocalizedDescriptionType>
  diplomaticPostCode?: number
  diplomaticPostNames?: Array<LocalizedDescriptionType>
}
