/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { HcpartyType } from "./HcpartyType"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

export class DmgInscription {
  constructor(json: JSON | any) {
    Object.assign(this as DmgInscription, json)
  }

  appliesTo?: string
  birthday?: Date
  commonOutput?: CommonOutput
  complete?: boolean
  deceased?: Date
  errors?: Array<MycarenetError>
  firstName?: string
  from?: Date
  hcParty?: HcpartyType
  inss?: string
  io?: string
  lastName?: string
  mutuality?: string
  mycarenetConversation?: MycarenetConversation
  payment1Amount?: number
  payment1Currency?: string
  payment1Date?: Date
  payment1Ref?: string
  payment2Amount?: number
  payment2Currency?: string
  payment2Date?: Date
  payment2Ref?: string
  reference?: string
  regNrWithMut?: string
  sex?: string
  to?: Date
  valueHash?: string
}
