/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { DmgAcknowledge } from "./DmgAcknowledge"
import { DmgClosure } from "./DmgClosure"
import { DmgExtension } from "./DmgExtension"
import { DmgInscription } from "./DmgInscription"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

import { decodeBase64 } from "./ModelHelper"

export class DmgsList {
  constructor(json: JSON | any) {
    Object.assign(this as DmgsList, json)
  }

  acks?: Array<DmgAcknowledge>
  appliesTo?: string
  closures?: Array<DmgClosure>
  commonOutput?: CommonOutput
  complete?: boolean
  date?: Date
  errors?: Array<MycarenetError>
  extensions?: Array<DmgExtension>
  inscriptions?: Array<DmgInscription>
  io?: string
  lists?: Array<DmgsList>
  mycarenetConversation?: MycarenetConversation
  reference?: string
  valueHash?: string
}
