/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SigningValue } from "./SigningValue"

import { decodeBase64 } from "./ModelHelper"

export class Document {
  constructor(json: JSON | any) {
    Object.assign(
      this as Document,
      json,
      json.content ? { content: decodeBase64(json.content) } : {}
    )
  }

  title?: string
  content?: ArrayBuffer
  textContent?: string
  filename?: string
  mimeType?: string
  signing?: SigningValue
}
