/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

import { decodeBase64 } from "./ModelHelper"

export class EAgreementResponse {
  constructor(json: JSON | any) {
    Object.assign(
      this as EAgreementResponse,
      json,
      json.content ? { content: decodeBase64(json.content) } : {},
      json.xades ? { xades: decodeBase64(json.xades) } : {}
    )
  }

  acknowledged?: boolean
  commonOutput?: CommonOutput
  content?: ArrayBuffer
  errors?: Array<MycarenetError>
  mycarenetConversation?: MycarenetConversation
  warnings?: Array<MycarenetError>
  xades?: ArrayBuffer
}
