/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class EattestCardReading {
  constructor(json: JSON | any) {
    Object.assign(this as EattestCardReading, json)
  }

  date?: number
  inputType?: number
  manualInputReason?: number
  mediaType?: number
  serial?: string
  time?: number
  vignetteReason?: number
}
