/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { EattestCardReading } from "./EattestCardReading"
import { EattestHcParty } from "./EattestHcParty"
import { EattestRequestor } from "./EattestRequestor"

export class EattestCode {
  constructor(json: JSON | any) {
    Object.assign(this as EattestCode, json)
  }

  cardReading?: EattestCardReading
  date?: number
  doctorSupplement?: number
  fee?: number
  gmdManager?: EattestHcParty
  internship?: EattestHcParty
  justification?: string
  location?: EattestHcParty
  locationService?: number
  norm?: number
  quantity?: number
  reglementarySupplement?: number
  reimbursement?: number
  relativeService?: string
  requestor?: EattestRequestor
  requestorNorm?: number
  riziv?: string
  side?: EattestCode.SideEnum
  transplantationCode?: EattestCode.TransplantationCodeEnum
}
export namespace EattestCode {
  export type SideEnum = "None" | "Left" | "Right"
  export const SideEnum = {
    None: "None" as SideEnum,
    Left: "Left" as SideEnum,
    Right: "Right" as SideEnum
  }
  export type TransplantationCodeEnum = "None" | "RefersToRecipient" | "RefersToDonor"
  export const TransplantationCodeEnum = {
    None: "None" as TransplantationCodeEnum,
    RefersToRecipient: "RefersToRecipient" as TransplantationCodeEnum,
    RefersToDonor: "RefersToDonor" as TransplantationCodeEnum
  }
}
