/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CipherData } from "./CipherData"
import { EncryptionMethodType } from "./EncryptionMethodType"
import { EncryptionProperties } from "./EncryptionProperties"
import { KeyInfo } from "./KeyInfo"
import { ReferenceList } from "./ReferenceList"

export class EncryptedKey {
  constructor(json: JSON | any) {
    Object.assign(this as EncryptedKey, json)
  }

  carriedKeyName?: string
  cipherData?: CipherData
  encoding?: string
  encryptionMethod?: EncryptionMethodType
  encryptionProperties?: EncryptionProperties
  id?: string
  keyInfo?: KeyInfo
  mimeType?: string
  recipient?: string
  referenceList?: ReferenceList
  type?: string
}
