/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDERROR } from "./CDERROR"
import { IDKMEHR } from "./IDKMEHR"
import { TextType } from "./TextType"

import { decodeBase64 } from "./ModelHelper"

export class ErrorType {
  constructor(json: JSON | any) {
    Object.assign(this as ErrorType, json)
  }

  cds?: Array<CDERROR>
  description?: TextType
  ids?: Array<IDKMEHR>
  url?: string
}
