/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export class FlatFileMetadata {
  constructor(json: JSON | any) {
    Object.assign(this as FlatFileMetadata, json)
  }

  amount?: number
  amountPerOAMap?: { [key: string]: Array<number> }
  codes?: Array<number>
  codesPerOAMap?: { [key: string]: Array<number> }
  recordsCount?: number
  recordsCountPerOAMap?: { [key: string]: Array<number> }
}
