/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { MycarenetConversation } from "./MycarenetConversation"
import { TAck } from "./TAck"

export class GenAsyncResponse {
  constructor(json: JSON | any) {
    Object.assign(this as GenAsyncResponse, json)
  }

  commonOutput?: CommonOutput
  mycarenetConversation?: MycarenetConversation
  result?: boolean
  tack?: TAck
}
