/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Base64EncodedKmehr } from "./Base64EncodedKmehr"
import { VaccinationStatusType } from "./VaccinationStatusType"

import { decodeBase64 } from "./ModelHelper"

export class GetVaccinationsResponseType {
  constructor(json: JSON | any) {
    Object.assign(this as GetVaccinationsResponseType, json)
  }

  base64EncodedKmehr?: Base64EncodedKmehr
  patientId?: string
  status?: VaccinationStatusType
}
