/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from "./AddressType"
import { CDHCPARTY } from "./CDHCPARTY"
import { IDHCPARTY } from "./IDHCPARTY"
import { TelecomType } from "./TelecomType"

export class HcpartyType {
  constructor(json: JSON | any) {
    Object.assign(this as HcpartyType, json)
  }

  addresses?: Array<AddressType>
  cds?: Array<CDHCPARTY>
  familyname?: string
  firstname?: string
  ids?: Array<IDHCPARTY>
  name?: string
  telecoms?: Array<TelecomType>
}
