/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class IDPROFESSION {
  constructor(json: JSON | any) {
    Object.assign(this as IDPROFESSION, json)
  }

  s?: IDPROFESSION.SEnum
  sl?: string
  sv?: string
  value?: string
}
export namespace IDPROFESSION {
  export type SEnum = "ID_MEDEX" | "ID_CBE"
  export const SEnum = {
    MEDEX: "ID_MEDEX" as SEnum,
    CBE: "ID_CBE" as SEnum
  }
}
