/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IDINSURANCE } from "./IDINSURANCE"
import { Personalpart } from "./Personalpart"
import { Thirdpayercontract } from "./Thirdpayercontract"
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

import { decodeBase64 } from "./ModelHelper"

export class InsuranceType {
  constructor(json: JSON | any) {
    Object.assign(this as InsuranceType, json)
  }

  approvalnumber?: string
  begindate?: XMLGregorianCalendar
  begindatepayment?: XMLGregorianCalendar
  cg1?: string
  cg2?: string
  enddate?: XMLGregorianCalendar
  id?: IDINSURANCE
  membership?: string
  personalparts?: Array<Personalpart>
  siscard?: string
  socialfranchiseperiod1?: string
  socialfranchiseperiod2?: string
  thirdpayercontract?: Thirdpayercontract
}
