/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from "./models"

export class ItemType {
  constructor(json: JSON | any) {
    Object.assign(this as ItemType, json)
  }
  author?: models.AuthorType

  batch?: string

  beginmoment?: models.MomentType

  cds?: Array<models.CDITEM>

  certainty?: models.CertaintyType

  confidentiality?: models.ConfidentialityType

  contents?: Array<models.ContentType>

  cost?: models.CostType

  dayperiods?: Array<models.DayperiodType>

  deliverydate?: Date

  duration?: models.DurationType

  endmoment?: models.MomentType

  feedback?: models.Feedback

  frequency?: models.FrequencyType

  ids?: Array<models.IDKMEHR>

  instructionforoverdosing?: models.TextType

  instructionforpatient?: models.TextType

  instructionforreimbursement?: models.TextType

  iscomplete?: boolean

  isrelevant?: boolean

  issubstitutionallowed?: boolean

  isvalidated?: boolean

  lifecycle?: models.LifecycleType

  lnks?: Array<models.LnkType>

  locals?: Array<models.LocalitemattributeType>

  posology?: models.Posology

  quantity?: models.QuantityType

  recorddatetime?: Date

  regimen?: models.Regimen

  renewal?: models.RenewalType

  route?: models.RouteType

  severity?: models.SeverityType

  sites?: Array<models.SiteType>

  strength?: models.StrengthType

  temporality?: models.TemporalityType

  texts?: Array<models.TextType>

  urgency?: models.UrgencyType
}
