/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { QName } from "./QName"
import { Signature } from "./Signature"

import { decodeBase64 } from "./ModelHelper"

export class JAXBElementSignature {
  constructor(json: JSON | any) {
    Object.assign(this as JAXBElementSignature, json)
  }

  globalScope?: boolean
  name?: QName
  nil?: boolean
  typeSubstituted?: boolean
  value?: Signature
}
