/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Base64EncryptedDataType } from "./Base64EncryptedDataType"
import { ConfidentialityType } from "./ConfidentialityType"
import { EncryptedType } from "./EncryptedType"
import { FolderType } from "./FolderType"
import { HeaderType } from "./HeaderType"
import { JAXBElementSignature } from "./JAXBElementSignature"

import { decodeBase64 } from "./ModelHelper"

export class Kmehrmessage {
  constructor(json: JSON | any) {
    Object.assign(this as Kmehrmessage, json)
  }

  base64EncryptedData?: Base64EncryptedDataType
  confidentiality?: ConfidentialityType
  encryptedData?: EncryptedType
  folders?: Array<FolderType>
  header?: HeaderType
  signature?: JAXBElementSignature
}
