/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CbssStatusType } from "./CbssStatusType"
import { ConsultCarmedInterventionResponseType } from "./ConsultCarmedInterventionResponseType"
import { MedicalCardRegistryStatusType } from "./MedicalCardRegistryStatusType"
import { MycarenetConversation } from "./MycarenetConversation"

import { decodeBase64 } from "./ModelHelper"

export class MediprimaMdaResponse {
  constructor(json: JSON | any) {
    Object.assign(this as MediprimaMdaResponse, json)
  }

  cbssStatus?: CbssStatusType
  medicalStatus?: MedicalCardRegistryStatusType
  mycarenetConversation?: MycarenetConversation
  response?: ConsultCarmedInterventionResponseType
  status?: string
}
