/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AllowedSupplementsType } from "./AllowedSupplementsType"
import { CompanyListType } from "./CompanyListType"
import { PeriodType } from "./PeriodType"
import { PswcSupportType } from "./PswcSupportType"

import { decodeBase64 } from "./ModelHelper"

export class MedicalTransportationType {
  constructor(json: JSON | any) {
    Object.assign(this as MedicalTransportationType, json)
  }

  allowedSupplements?: AllowedSupplementsType
  amountPatientPartMax?: number
  companyList?: CompanyListType
  pswcSupport?: PswcSupportType
  validityPeriod?: PeriodType
}
