/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Code } from "./Code"

export class Medicinalproduct {
  constructor(json: JSON | any) {
    Object.assign(this as Medicinalproduct, json)
  }

  deliveredcds?: Array<Code>
  deliveredname?: string
  intendedcds?: Array<Code>
  intendedname?: string
  samId?: string
}
