/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { FaultType } from "./FaultType"
import { MemberDataAck } from "./MemberDataAck"
import { MemberDataMessage } from "./MemberDataMessage"
import { MycarenetConversation } from "./MycarenetConversation"

import { decodeBase64 } from "./ModelHelper"

export class MemberDataList {
  constructor(json: JSON | any) {
    Object.assign(this as MemberDataList, json)
  }

  acks?: Array<MemberDataAck>
  date?: Date
  genericErrors?: Array<FaultType>
  memberDataMessageList?: Array<MemberDataMessage>
  mycarenetConversation?: MycarenetConversation
}
