/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { FaultType } from "./FaultType"
import { MemberDataBatchResponse } from "./MemberDataBatchResponse"
import { MycarenetError } from "./MycarenetError"

import { decodeBase64 } from "./ModelHelper"

export class MemberDataMessage {
  constructor(json: JSON | any) {
    Object.assign(this as MemberDataMessage, json)
  }

  appliesTo?: string
  commonOutput?: CommonOutput
  complete?: boolean
  errors?: Array<MycarenetError>
  genericErrors?: Array<FaultType>
  io?: string
  memberDataResponse?: Array<MemberDataBatchResponse>
  reference?: string
  valueHash?: string
}
