/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Assertion } from "./Assertion"
import { CommonOutputType } from "./CommonOutputType"
import { FaultType } from "./FaultType"
import { MdaStatus } from "./MdaStatus"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

import { decodeBase64 } from "./ModelHelper"

export class MemberDataResponse {
  constructor(json: JSON | any) {
    Object.assign(this as MemberDataResponse, json)
  }

  assertions?: Array<Assertion>
  commonOutput?: CommonOutputType
  errors?: Array<FaultType>
  myCarenetErrors?: Array<MycarenetError>
  mycarenetConversation?: MycarenetConversation
  status?: MdaStatus
}
