/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Addressee } from "./Addressee"

export class Message {
  constructor(json: JSON | any) {
    Object.assign(this as Message, json)
  }

  customMetas?: { [key: string]: string }
  destinations?: Array<Addressee>
  encrypted?: boolean
  expirationDateTime?: number
  hasAnnex?: boolean
  hasFreeInformations?: boolean
  id?: string
  important?: boolean
  mandatee?: Addressee
  publicationDateTime?: number
  publicationId?: string
  sender?: Addressee
  size?: string
  usePublicationReceipt?: boolean
  useReadReceipt?: boolean
  useReceivedReceipt?: boolean
}
