/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TextType } from "./TextType"
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

import { decodeBase64 } from "./ModelHelper"

export class MomentType {
  constructor(json: JSON | any) {
    Object.assign(this as MomentType, json)
  }

  date?: Date
  text?: TextType
  time?: Date
  year?: XMLGregorianCalendar
  yearmonth?: XMLGregorianCalendar
}
