/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDPERIODICITY } from "./CDPERIODICITY"

export class PeriodicityType {
  constructor(json: JSON | any) {
    Object.assign(this as PeriodicityType, json)
  }

  cd?: CDPERIODICITY
}
