/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Address } from "./Address"
import { BirthPlace } from "./BirthPlace"

import { decodeBase64 } from "./ModelHelper"

export class PersonMid {
  constructor(json: JSON | any) {
    Object.assign(this as PersonMid, json)
  }

  lastName?: string
  firstName?: string
  nationalityCode?: string
  dateOfBirth?: number
  gender?: string
  birthPlace?: BirthPlace
  residentialAddress?: Address
}
