/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AnomaliesType } from "./AnomaliesType"
import { ContactAddressBaseType } from "./ContactAddressBaseType"
import { MinimalAddressType } from "./MinimalAddressType"
import { MinimalAdministratorType } from "./MinimalAdministratorType"
import { MinimalBirthInfoType } from "./MinimalBirthInfoType"
import { MinimalGenderInfoType } from "./MinimalGenderInfoType"
import { MinimalNameInfoType } from "./MinimalNameInfoType"

import { decodeBase64 } from "./ModelHelper"

export class PersonIdentificationType {
  constructor(json: JSON | any) {
    Object.assign(this as PersonIdentificationType, json)
  }

  address?: MinimalAddressType
  administrator?: MinimalAdministratorType
  anomalies?: AnomaliesType
  birth?: MinimalBirthInfoType
  contactAddress?: ContactAddressBaseType
  deceased?: boolean
  gender?: MinimalGenderInfoType
  name?: MinimalNameInfoType
  register?: string
  ssin?: string
}
