/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Kmehrmessage } from "./Kmehrmessage"

import { decodeBase64 } from "./ModelHelper"

export class Prescription {
  constructor(json: JSON | any) {
    Object.assign(this as Prescription, json)
  }

  creationDate?: Date
  decryptedContent?: Kmehrmessage
  encryptionKeyId?: string
  feedbackAllowed?: boolean
  notificationWasSent?: boolean
  patientId?: string
  prescriberId?: string
  requestXml?: string
  rid?: string
  status?: string
  validUntil?: Date
  visionByOthers?: string
}
