/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Denominator } from "./Denominator"
import { Nominator } from "./Nominator"
import { PeriodicityType } from "./PeriodicityType"
import { TextType } from "./TextType"
import { UnitType } from "./UnitType"

export class RecipefrequencyType {
  constructor(json: JSON | any) {
    Object.assign(this as RecipefrequencyType, json)
  }

  decimal?: number
  denominator?: Denominator
  nominator?: Nominator
  periodicity?: PeriodicityType
  text?: TextType
  unit?: UnitType
}
