/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from "./models"

export class RecipeCDITEM {
  constructor(json: JSON | any) {
    Object.assign(this as RecipeCDITEM, json)
  }
  dn?: string

  l?: string

  nullFlavor?: string

  s?: RecipeCDITEM.SEnum

  sl?: string

  sv?: string

  value?: string
}
export namespace RecipeCDITEM {
  export enum SEnum {
    CDITEM = <any>"CD_ITEM",
    CDITEMMAA = <any>"CD_ITEM_MAA",
    CDITEMCARENET = <any>"CD_ITEM_CARENET",
    CDLAB = <any>"CD_LAB",
    CDTECHNICAL = <any>"CD_TECHNICAL",
    CDCONTACTPERSON = <any>"CD_CONTACT_PERSON",
    ICD = <any>"ICD",
    ICPC = <any>"ICPC",
    LOCAL = <any>"LOCAL",
    CDVACCINE = <any>"CD_VACCINE",
    CDECG = <any>"CD_ECG",
    CDECARECLINICAL = <any>"CD_ECARE_CLINICAL",
    CDECARELAB = <any>"CD_ECARE_LAB",
    CDECAREHAQ = <any>"CD_ECARE_HAQ",
    CDITEMEBIRTH = <any>"CD_ITEM_EBIRTH",
    CDPARAMETER = <any>"CD_PARAMETER",
    CDITEMBVT = <any>"CD_ITEM_BVT",
    CDBVTAVAILABLEMATERIALS = <any>"CD_BVT_AVAILABLEMATERIALS",
    CDBVTCONSERVATIONDELAY = <any>"CD_BVT_CONSERVATIONDELAY",
    CDBVTCONSERVATIONMODE = <any>"CD_BVT_CONSERVATIONMODE",
    CDBVTSAMPLETYPE = <any>"CD_BVT_SAMPLETYPE",
    CDBCRDIFFERENTATIONDEGREE = <any>"CD_BCR_DIFFERENTATIONDEGREE",
    CDBVTLATERALITY = <any>"CD_BVT_LATERALITY",
    CDBVTPATIENTOPPOSITION = <any>"CD_BVT_PATIENTOPPOSITION",
    CDBVTSTATUS = <any>"CD_BVT_STATUS",
    CDITEMREG = <any>"CD_ITEM_REG",
    CDITEMMYCARENET = <any>"CD_ITEM_MYCARENET",
    CDDEFIBDIAGNOSIS = <any>"CD_DEFIB_DIAGNOSIS",
    CDACTSNURSING = <any>"CD_ACTS_NURSING",
    CDQERMIDINTERVENTIONTYPE = <any>"CD_QERMID_INTERVENTIONTYPE"
  }
}
