/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class RecipeCDITEM {
  constructor(json: JSON | any) {
    Object.assign(this as RecipeCDITEM, json)
  }

  dn?: string
  l?: string
  nullFlavor?: string
  s?: RecipeCDITEM.SEnum
  sl?: string
  sv?: string
  value?: string
}
export namespace RecipeCDITEM {
  export type SEnum =
    | "CD_ITEM"
    | "CD_ITEM_MAA"
    | "CD_ITEM_CARENET"
    | "CD_LAB"
    | "CD_TECHNICAL"
    | "CD_CONTACT_PERSON"
    | "ICD"
    | "ICPC"
    | "LOCAL"
    | "CD_VACCINE"
    | "CD_ECG"
    | "CD_ECARE_CLINICAL"
    | "CD_ECARE_LAB"
    | "CD_ECARE_HAQ"
    | "CD_ITEM_EBIRTH"
    | "CD_PARAMETER"
    | "CD_ITEM_BVT"
    | "CD_BVT_AVAILABLEMATERIALS"
    | "CD_BVT_CONSERVATIONDELAY"
    | "CD_BVT_CONSERVATIONMODE"
    | "CD_BVT_SAMPLETYPE"
    | "CD_BCR_DIFFERENTATIONDEGREE"
    | "CD_BVT_LATERALITY"
    | "CD_BVT_PATIENTOPPOSITION"
    | "CD_BVT_STATUS"
    | "CD_ITEM_REG"
    | "CD_ITEM_MYCARENET"
    | "CD_DEFIB_DIAGNOSIS"
    | "CD_ACTS_NURSING"
    | "CD_QERMID_INTERVENTIONTYPE"
  export const SEnum = {
    CDITEM: "CD_ITEM" as SEnum,
    CDITEMMAA: "CD_ITEM_MAA" as SEnum,
    CDITEMCARENET: "CD_ITEM_CARENET" as SEnum,
    CDLAB: "CD_LAB" as SEnum,
    CDTECHNICAL: "CD_TECHNICAL" as SEnum,
    CDCONTACTPERSON: "CD_CONTACT_PERSON" as SEnum,
    ICD: "ICD" as SEnum,
    ICPC: "ICPC" as SEnum,
    LOCAL: "LOCAL" as SEnum,
    CDVACCINE: "CD_VACCINE" as SEnum,
    CDECG: "CD_ECG" as SEnum,
    CDECARECLINICAL: "CD_ECARE_CLINICAL" as SEnum,
    CDECARELAB: "CD_ECARE_LAB" as SEnum,
    CDECAREHAQ: "CD_ECARE_HAQ" as SEnum,
    CDITEMEBIRTH: "CD_ITEM_EBIRTH" as SEnum,
    CDPARAMETER: "CD_PARAMETER" as SEnum,
    CDITEMBVT: "CD_ITEM_BVT" as SEnum,
    CDBVTAVAILABLEMATERIALS: "CD_BVT_AVAILABLEMATERIALS" as SEnum,
    CDBVTCONSERVATIONDELAY: "CD_BVT_CONSERVATIONDELAY" as SEnum,
    CDBVTCONSERVATIONMODE: "CD_BVT_CONSERVATIONMODE" as SEnum,
    CDBVTSAMPLETYPE: "CD_BVT_SAMPLETYPE" as SEnum,
    CDBCRDIFFERENTATIONDEGREE: "CD_BCR_DIFFERENTATIONDEGREE" as SEnum,
    CDBVTLATERALITY: "CD_BVT_LATERALITY" as SEnum,
    CDBVTPATIENTOPPOSITION: "CD_BVT_PATIENTOPPOSITION" as SEnum,
    CDBVTSTATUS: "CD_BVT_STATUS" as SEnum,
    CDITEMREG: "CD_ITEM_REG" as SEnum,
    CDITEMMYCARENET: "CD_ITEM_MYCARENET" as SEnum,
    CDDEFIBDIAGNOSIS: "CD_DEFIB_DIAGNOSIS" as SEnum,
    CDACTSNURSING: "CD_ACTS_NURSING" as SEnum,
    CDQERMIDINTERVENTIONTYPE: "CD_QERMID_INTERVENTIONTYPE" as SEnum
  }
}
