/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TextType } from "./TextType"
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

export class RecipemomentType {
  constructor(json: JSON | any) {
    Object.assign(this as RecipemomentType, json)
  }

  date?: XMLGregorianCalendar
  text?: TextType
  time?: XMLGregorianCalendar
  year?: XMLGregorianCalendar
  yearmonth?: XMLGregorianCalendar
}
