/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressType } from "./AddressType"
import { AddressTypeBase } from "./AddressTypeBase"
import { Civilstate } from "./Civilstate"
import { DateType } from "./DateType"
import { IDPATIENT } from "./IDPATIENT"
import { InsuranceType } from "./InsuranceType"
import { MemberinsuranceType } from "./MemberinsuranceType"
import { Nationality } from "./Nationality"
import { ProfessionType } from "./ProfessionType"
import { SexType } from "./SexType"
import { TelecomType } from "./TelecomType"
import { TextType } from "./TextType"
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

export class RecipepatientpersonType {
  constructor(json: JSON | any) {
    Object.assign(this as RecipepatientpersonType, json)
  }

  addresses?: Array<AddressType>
  birthdate?: DateType
  birthlocation?: AddressTypeBase
  civilstate?: Civilstate
  deathdate?: DateType
  deathlocation?: AddressTypeBase
  familyname?: string
  firstnames?: Array<string>
  ids?: Array<IDPATIENT>
  insurancymembership?: MemberinsuranceType
  insurancystatus?: InsuranceType
  nationality?: Nationality
  profession?: ProfessionType
  recorddatetime?: XMLGregorianCalendar
  sex?: SexType
  telecoms?: Array<TelecomType>
  texts?: Array<TextType>
  usuallanguage?: string
}
