/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class RecipeCDTRANSACTION {
  constructor(json: JSON | any) {
    Object.assign(this as RecipeCDTRANSACTION, json)
  }

  dn?: string
  l?: string
  s?: RecipeCDTRANSACTION.SEnum
  sl?: string
  sv?: string
  value?: string
}
export namespace RecipeCDTRANSACTION {
  export type SEnum =
    | "CD_TRANSACTION"
    | "CD_TRANSACTION_CARENET"
    | "CD_TRANSACTION_MAA"
    | "CD_CHAPTER_4_APPENDIX"
    | "CD_TRANSACTION_REG"
    | "CD_TRANSACTION_MYCARENET"
    | "CD_TRANSACTION_TYPE"
    | "CD_HUBSERVICE"
    | "LOCAL"
  export const SEnum = {
    CDTRANSACTION: "CD_TRANSACTION" as SEnum,
    CDTRANSACTIONCARENET: "CD_TRANSACTION_CARENET" as SEnum,
    CDTRANSACTIONMAA: "CD_TRANSACTION_MAA" as SEnum,
    CDCHAPTER4APPENDIX: "CD_CHAPTER_4_APPENDIX" as SEnum,
    CDTRANSACTIONREG: "CD_TRANSACTION_REG" as SEnum,
    CDTRANSACTIONMYCARENET: "CD_TRANSACTION_MYCARENET" as SEnum,
    CDTRANSACTIONTYPE: "CD_TRANSACTION_TYPE" as SEnum,
    CDHUBSERVICE: "CD_HUBSERVICE" as SEnum,
    LOCAL: "LOCAL" as SEnum
  }
}
