/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DigestMethod } from "./DigestMethod"
import { Transforms } from "./Transforms"

import { decodeBase64 } from "./ModelHelper"

export class Reference {
  constructor(json: JSON | any) {
    Object.assign(
      this as Reference,
      json,
      json.digestValue ? { digestValue: decodeBase64(json.digestValue) } : {}
    )
  }

  digestMethod?: DigestMethod
  digestValue?: ArrayBuffer
  id?: string
  transforms?: Transforms
  type?: string
  uri?: string
}
