/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { NameType } from "./NameType"
import { PodmiSppisPartType } from "./PodmiSppisPartType"

import { decodeBase64 } from "./ModelHelper"

export class RefundPodmiSppisType {
  constructor(json: JSON | any) {
    Object.assign(this as RefundPodmiSppisType, json)
  }

  affiliedMutualityInd?: boolean
  beneficiaryStatus?: string
  justification?: Array<NameType>
  medicalUrgencyInd?: boolean
  podmiSppisPart?: PodmiSppisPartType
  refundCode?: number
}
