/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Exception } from "./Exception"
import { RnConsultConversationDto } from "./RnConsultConversationDto"
import { RnConsultSearchByNissResultDto } from "./RnConsultSearchByNissResultDto"
import { SsinWithCanceledAndReplacesStatusType } from "./SsinWithCanceledAndReplacesStatusType"
import { Status } from "./Status"

import { decodeBase64 } from "./ModelHelper"

export class RnConsultSearchPersonBySsinResponseDto {
  constructor(json: JSON | any) {
    Object.assign(this as RnConsultSearchPersonBySsinResponseDto, json)
  }

  exception?: Exception
  id?: string
  inResponseTo?: string
  issueInstant?: Date
  result?: RnConsultSearchByNissResultDto
  ssin?: SsinWithCanceledAndReplacesStatusType
  status?: Status
  xmlConversations?: RnConsultConversationDto
}
