/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BirthPlace } from "./BirthPlace"
import { ContactAddress } from "./ContactAddress"
import { ResidentialAddress } from "./ResidentialAddress"

import { decodeBase64 } from "./ModelHelper"

export class RnConsultPersonMid {
  constructor(json: JSON | any) {
    Object.assign(this as RnConsultPersonMid, json)
  }

  firstName?: string
  lastName?: string
  middleName?: string
  nationalityCode?: number
  dateOfBirth?: number
  birthPlace?: BirthPlace
  gender?: string
  residentialAddress?: ResidentialAddress
  contactAddress?: ContactAddress
  language?: string
}
