/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AddressBaseType } from "./AddressBaseType"
import { AdministratorBaseType } from "./AdministratorBaseType"
import { AnomaliesType } from "./AnomaliesType"
import { BirthInfoBaseType } from "./BirthInfoBaseType"
import { CivilStatesBaseType } from "./CivilStatesBaseType"
import { ContactAddressBaseType } from "./ContactAddressBaseType"
import { GenderInfoBaseType } from "./GenderInfoBaseType"
import { LegalCohabitationBaseType } from "./LegalCohabitationBaseType"
import { NationalitiesBaseType } from "./NationalitiesBaseType"
import { NobilityTitleBaseType } from "./NobilityTitleBaseType"
import { RnConsultDeceaseType } from "./RnConsultDeceaseType"
import { RnConsultNameType } from "./RnConsultNameType"
import { SubregisterBaseType } from "./SubregisterBaseType"

import { decodeBase64 } from "./ModelHelper"

export class RnConsultPersonDto {
  constructor(json: JSON | any) {
    Object.assign(this as RnConsultPersonDto, json)
  }

  address?: AddressBaseType
  administrator?: AdministratorBaseType
  anomalies?: AnomaliesType
  birth?: BirthInfoBaseType
  civilStates?: CivilStatesBaseType
  contactAddress?: ContactAddressBaseType
  decease?: RnConsultDeceaseType
  gender?: GenderInfoBaseType
  legalCohabitation?: LegalCohabitationBaseType
  name?: RnConsultNameType
  nationalities?: NationalitiesBaseType
  nobilityTitle?: NobilityTitleBaseType
  register?: string
  registerInceptionDate?: Date
  ssin?: string
  subregister?: SubregisterBaseType
}
