/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ActivePattern } from "./ActivePattern"
import { FailedAssert } from "./FailedAssert"
import { FiredRule } from "./FiredRule"
import { Ns } from "./Ns"
import { NsPrefixInAttributeValues } from "./NsPrefixInAttributeValues"
import { SuccessfulReport } from "./SuccessfulReport"

import { decodeBase64 } from "./ModelHelper"

export class SchematronOutput {
  constructor(json: JSON | any) {
    Object.assign(this as SchematronOutput, json)
  }

  activePattern?: Array<ActivePattern>
  failedAssert?: Array<FailedAssert>
  firedRule?: Array<FiredRule>
  ns?: Array<Ns>
  nsPrefixInAttributeValues?: Array<NsPrefixInAttributeValues>
  phase?: string
  schemaVersion?: string
  successfulReport?: Array<SuccessfulReport>
  text?: Array<string>
  title?: string
}
