/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { KeyInfo } from "./KeyInfo"
import { SignatureValue } from "./SignatureValue"
import { SignedInfo } from "./SignedInfo"

import { decodeBase64 } from "./ModelHelper"

export class Signature {
  constructor(json: JSON | any) {
    Object.assign(this as Signature, json)
  }

  id?: string
  keyInfo?: KeyInfo
  objects?: Array<any>
  signatureValue?: SignatureValue
  signedInfo?: SignedInfo
}
