/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDSTANDARD } from "./CDSTANDARD"
import { Specialisation } from "./Specialisation"

export class StandardType {
  constructor(json: JSON | any) {
    Object.assign(this as StandardType, json)
  }

  cd?: CDSTANDARD
  specialisation?: Specialisation
}
