/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CommonOutput } from "./CommonOutput"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

export class StartSubscriptionResultWithResponse {
  constructor(json: JSON | any) {
    Object.assign(this as StartSubscriptionResultWithResponse, json)
  }

  commonOutput?: CommonOutput
  errors?: Array<MycarenetError>
  inscriptionDate?: number
  kmehrMessage?: Array<string>
  mycarenetConversation?: MycarenetConversation
  reference?: string
  subscriptionsStartDate?: number
  xades?: Array<string>
}
