/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XMLGregorianCalendar } from "./XMLGregorianCalendar"

export class SubjectConfirmationDataType {
  constructor(json: JSON | any) {
    Object.assign(this as SubjectConfirmationDataType, json)
  }

  address?: string
  content?: Array<any>
  inResponseTo?: string
  notBefore?: XMLGregorianCalendar
  notOnOrAfter?: XMLGregorianCalendar
  otherAttributes?: { [key: string]: string }
  recipient?: string
}
