/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { BaseID } from "./BaseID"
import { EncryptedElementType } from "./EncryptedElementType"
import { NameIDType } from "./NameIDType"
import { SubjectConfirmationDataType } from "./SubjectConfirmationDataType"

export class SubjectConfirmation {
  constructor(json: JSON | any) {
    Object.assign(this as SubjectConfirmation, json)
  }

  baseID?: BaseID
  encryptedID?: EncryptedElementType
  method?: string
  nameID?: NameIDType
  subjectConfirmationData?: SubjectConfirmationDataType
}
