/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import { decodeBase64 } from "./ModelHelper"

export class TAck {
  constructor(json: JSON | any) {
    Object.assign(this as TAck, json, json.value ? { value: decodeBase64(json.value) } : {})
  }

  appliesTo?: string
  id?: string
  issuer?: string
  reference?: string
  resultMajor?: string
  resultMessage?: string
  resultMinor?: string
  value?: ArrayBuffer
}
