/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Author } from "./Author"
import { CodeResult } from "./CodeResult"
import { CommonOutput } from "./CommonOutput"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"
import { Patient } from "./Patient"

import { decodeBase64 } from "./ModelHelper"

export class TarificationMediprimaConsultationResult {
  constructor(json: JSON | any) {
    Object.assign(this as TarificationMediprimaConsultationResult, json)
  }

  author?: Author
  codeResults?: Array<CodeResult>
  commonOutput?: CommonOutput
  errors?: Array<MycarenetError>
  mycarenetConversation?: MycarenetConversation
  patient?: Patient
}
