/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CodeResult } from "./CodeResult"
import { CommonOutput } from "./CommonOutput"
import { MycarenetConversation } from "./MycarenetConversation"
import { MycarenetError } from "./MycarenetError"

export class TarificationConsultationResult {
  constructor(json: JSON | any) {
    Object.assign(this as TarificationConsultationResult, json)
  }

  birthdate?: Date
  codeResults?: Array<CodeResult>
  commonOutput?: CommonOutput
  ct1?: string
  ct2?: string
  date?: Date
  deceased?: Date
  errors?: Array<MycarenetError>
  firstName?: string
  insurancePeriodEnd?: Date
  insurancePeriodStart?: Date
  lastName?: string
  mycarenetConversation?: MycarenetConversation
  niss?: string
  sex?: TarificationConsultationResult.SexEnum
}
export namespace TarificationConsultationResult {
  export type SexEnum = "MALE" | "FEMALE"
  export const SexEnum = {
    MALE: "MALE" as SexEnum,
    FEMALE: "FEMALE" as SexEnum
  }
}
