/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { CDTELECOM } from "./CDTELECOM"
import { IDKMEHR } from "./IDKMEHR"

import { decodeBase64 } from "./ModelHelper"

export class TelecomType {
  constructor(json: JSON | any) {
    Object.assign(this as TelecomType, json)
  }

  cds?: Array<CDTELECOM>
  ids?: Array<IDKMEHR>
  telecomnumber?: string
}
