/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { HcpartyType } from "./HcpartyType"
import { PatientIdType } from "./PatientIdType"
import { TransactionWithSpecificTime } from "./TransactionWithSpecificTime"

export class Transactionaccess {
  constructor(json: JSON | any) {
    Object.assign(this as Transactionaccess, json)
  }

  accessdatetime?: Date
  breaktheglass?: string
  hcparties?: Array<HcpartyType>
  patient?: PatientIdType
  transaction?: TransactionWithSpecificTime
}
