/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { AuthorDto } from "./AuthorDto"
import { KmehrCd } from "./KmehrCd"
import { KmehrId } from "./KmehrId"

export class TransactionSummaryDto {
  constructor(json: JSON | any) {
    Object.assign(this as TransactionSummaryDto, json)
  }

  author?: AuthorDto
  authorsList?: string
  cds?: Array<KmehrCd>
  date?: number
  desc?: string
  ids?: Array<KmehrId>
  iscomplete?: boolean
  isvalidated?: boolean
  recorddatetime?: number
  time?: number
}
