/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Status } from "./Status"
import { ValidationResult } from "./ValidationResult"

import { decodeBase64 } from "./ModelHelper"

export class VerifyIdResponse {
  constructor(json: JSON | any) {
    Object.assign(this as VerifyIdResponse, json)
  }

  id?: string
  inResponseTo?: string
  issueInstant?: Date
  status?: Status
  validationResult?: ValidationResult
}
