/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { Consent } from "../model/Consent"
import { GetAccessRightResponse } from "../model/GetAccessRightResponse"
import { GetPatientAuditTrailResponse } from "../model/GetPatientAuditTrailResponse"
import { HcPartyConsentDto } from "../model/HcPartyConsentDto"
import { Kmehrmessage } from "../model/Kmehrmessage"
import { Patient } from "../model/Patient"
import { PutAccessRightResponse } from "../model/PutAccessRightResponse"
import { PutPatientConsentResponse } from "../model/PutPatientConsentResponse"
import { PutTherapeuticLinkResponse } from "../model/PutTherapeuticLinkResponse"
import { PutTransactionResponseDto } from "../model/PutTransactionResponseDto"
import { PutTransactionSetResponse } from "../model/PutTransactionSetResponse"
import { RevokeAccessRightResponse } from "../model/RevokeAccessRightResponse"
import { RevokePatientConsentResponse } from "../model/RevokePatientConsentResponse"
import { RevokeTherapeuticLinkResponse } from "../model/RevokeTherapeuticLinkResponse"
import { TherapeuticLinkMessageDto } from "../model/TherapeuticLinkMessageDto"
import { TransactionSummaryDto } from "../model/TransactionSummaryDto"

export class fhcHubApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(
    host: string,
    headers: any,
    fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>
  ) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }

  /**
   * This endpoint converts a Kmehr XML message to a JSON representation. It is useful for applications that need to process Kmehr messages in JSON format.
   * @summary Utlity method to convert Kmehr XML to JSON
   * @param body message
   */
  convertKmehrXMLtoJSONUsingPOST(body?: string): Promise<Kmehrmessage> {
    let _body = null
    _body = body

    const _url = this.host + `/hub/convertKmehrXMLtoJSON` + "?ts=" + new Date().getTime()
    let headers = this.headers
    headers = headers
      .filter(h => h.header !== "Content-Type")
      .concat(new XHR.Header("Content-Type", "application/xml"))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new Kmehrmessage(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to check the access rights of another healthcare provider to access a patient's data. It requires the healthcare provider's information and the identifiers of the document and the rights that need to be checked.
   * @summary Get the access right for a healthcare provider to access a patient's data
   * @param endpoint Endpoint URL of the hub (e.g., https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, etc.)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param sv The SV part of the identifier of the transaction. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction. Obtained from the transaction list.
   * @param value The value of the transaction to manage, usually the ID of the transaction
   * @param hubPackageId The hub package ID, provided by the hub. This ID is usually different for acceptance and production environments.
   */
  getAccessRightUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    sv: string,
    sl: string,
    value: string,
    hubPackageId?: string
  ): Promise<GetAccessRightResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/access` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (sv ? "&sv=" + encodeURIComponent(String(sv)) : "") +
      (sl ? "&sl=" + encodeURIComponent(String(sl)) : "") +
      (value ? "&value=" + encodeURIComponent(String(value)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new GetAccessRightResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve the consent status of a healthcare provider that determines if an hcp has the right to access the hub. It requires the healthcare provider's information.
   * @summary Get the consent status of a healthcare provider
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   */
  getHcpConsentUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpNihii: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpSsin: string,
    hcpZip: string,
    hubPackageId?: string
  ): Promise<HcPartyConsentDto> {
    let _body = null

    const _url =
      this.host +
      `/hub/hcpconsent/${encodeURIComponent(String(hcpNihii))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new HcPartyConsentDto(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve the audit trail of a patient. It requires the healthcare provider's information, the patient's SSIN, and the hub package ID. The date range, author information, and transaction types can be provided to filter the results.
   * @summary Get the audit trail of a patient
   * @param endpoint value &#x3D; &#x27;The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)&#x27;
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param hubPackageId The hub package ID, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param from The start date of the search for transactions in format YYYYMMDD
   * @param to The end date of the search for transactions in format YYYYMMDD
   * @param authorNihii The Nihii of the author of the transaction, optional
   * @param authorSsin The SSIN of the author of the transaction, optional
   * @param isGlobal Whether the transaction search is global (on all hubs through intrahub) or local (on the hub where the request is made)
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   * @param ssin The SSIN of the patient, optional
   * @param sv The SV part of the identifier of the transaction, optional
   * @param sl The SL part of the identifier of the transaction, optional
   * @param id The ID of the transaction, optional
   */
  getPatientAuditTrailUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    hubPackageId?: string,
    from?: number,
    to?: number,
    authorNihii?: string,
    authorSsin?: string,
    isGlobal?: boolean,
    breakTheGlassReason?: string,
    ssin?: string,
    sv?: string,
    sl?: string,
    id?: string
  ): Promise<GetPatientAuditTrailResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/trail` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (from ? "&from=" + encodeURIComponent(String(from)) : "") +
      (to ? "&to=" + encodeURIComponent(String(to)) : "") +
      (authorNihii ? "&authorNihii=" + encodeURIComponent(String(authorNihii)) : "") +
      (authorSsin ? "&authorSsin=" + encodeURIComponent(String(authorSsin)) : "") +
      (isGlobal ? "&isGlobal=" + encodeURIComponent(String(isGlobal)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "") +
      (ssin ? "&ssin=" + encodeURIComponent(String(ssin)) : "") +
      (sv ? "&sv=" + encodeURIComponent(String(sv)) : "") +
      (sl ? "&sl=" + encodeURIComponent(String(sl)) : "") +
      (id ? "&id=" + encodeURIComponent(String(id)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new GetPatientAuditTrailResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve a patient's consent from the hubs, in other words, the patient's consent of having institutions and healthcare providers put some information on the hubs. It requires the healthcare provider's information and the patient's SSIN.
   * @summary Get a patient's consent
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   */
  getPatientConsentUsingGET1(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string
  ): Promise<Consent> {
    let _body = null

    const _url =
      this.host +
      `/hub/consent/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new Consent(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve a patient's information from the hubs. It requires the healthcare provider's information and the patient's SSIN.
   * @summary Get a patient from the hubs
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare party
   * @param hcpFirstName The first name of the healthcare party
   * @param hcpNihii The Nihii of the healthcare party
   * @param hcpSsin The SSIN of the healthcare party
   * @param hcpZip The ZIP code of the healthcare party
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   */
  getPatientUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string
  ): Promise<Patient> {
    let _body = null

    const _url =
      this.host +
      `/hub/patient/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new Patient(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve therapeutic links for a patient. It requires the healthcare provider's information, the patient's SSIN, and some optional parameters such as the type of therapeutic link, start and end dates.
   * @summary Get therapeutic links for a patient
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param therLinkType The type of the therapeutic link to retrieve
   * @param from The start date of the therapeutic link in format YYYYMMDD
   * @param to The end date of the therapeutic link in format YYYYMMDD
   */
  getTherapeuticLinksUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string,
    therLinkType?: string,
    from?: number,
    to?: number
  ): Promise<TherapeuticLinkMessageDto> {
    let _body = null

    const _url =
      this.host +
      `/hub/therlink/${encodeURIComponent(String(hcpNihii))}/${encodeURIComponent(
        String(patientSsin)
      )}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (therLinkType ? "&therLinkType=" + encodeURIComponent(String(therLinkType)) : "") +
      (from ? "&from=" + encodeURIComponent(String(from)) : "") +
      (to ? "&to=" + encodeURIComponent(String(to)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new TherapeuticLinkMessageDto(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve a specific transaction message for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction ID.
   * @summary Get a transaction of type message for a patient converted to JSON for easy frontend parsing
   * @param endpoint Endpoint URL of the hub (e.g., https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, etc.)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param ssin The SSIN of the patient
   * @param sv The SV part of the identifier of the transaction. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction. Obtained from the transaction list.
   * @param id The ID of the transaction to retrieve
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   * @param externalHubId The ID of the hub (1990000035 for RSW, 1990000728 for Abrumet, 1990000134 for Cozo, 1990001916 for Vitalink, ...)
   * @param externalHubName The name of the hub
   */
  getTransactionMessageUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    ssin: string,
    sv: string,
    sl: string,
    id: string,
    hubPackageId?: string,
    breakTheGlassReason?: string,
    externalHubId?: string,
    externalHubName?: string
  ): Promise<Kmehrmessage> {
    let _body = null

    const _url =
      this.host +
      `/hub/t/${encodeURIComponent(String(ssin))}/${encodeURIComponent(
        String(sv)
      )}/${encodeURIComponent(String(sl))}/kmehr` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (id ? "&id=" + encodeURIComponent(String(id)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "") +
      (externalHubId ? "&externalHubId=" + encodeURIComponent(String(externalHubId)) : "") +
      (externalHubName ? "&externalHubName=" + encodeURIComponent(String(externalHubName)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new Kmehrmessage(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve a transaction set for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction set identifier.
   * @summary Get a transaction set (a collection of transactions) for a patient. This is mainly used for medication schemes. Returns the message in JSON format for easy frontend parsing.
   * @param endpoint Endpoint URL of the hub (e.g., https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, etc.)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param ssin The SSIN of the patient
   * @param sv The SV part of the identifier of the transaction set. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction set. Obtained from the transaction list.
   * @param id The ID of the transaction set to retrieve
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   * @param externalHubId The ID of the hub (1990000035 for RSW, 1990000728 for Abrumet, 1990000134 for Cozo, 1990001916 for Vitalink, ...)
   * @param externalHubName The name of the hub
   */
  getTransactionSetMessageUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    ssin: string,
    sv: string,
    sl: string,
    id: string,
    hubPackageId?: string,
    breakTheGlassReason?: string,
    externalHubId?: string,
    externalHubName?: string
  ): Promise<Kmehrmessage> {
    let _body = null

    const _url =
      this.host +
      `/hub/ts/${encodeURIComponent(String(ssin))}/${encodeURIComponent(
        String(sv)
      )}/${encodeURIComponent(String(sl))}/kmehr` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (id ? "&id=" + encodeURIComponent(String(id)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "") +
      (externalHubId ? "&externalHubId=" + encodeURIComponent(String(externalHubId)) : "") +
      (externalHubName ? "&externalHubName=" + encodeURIComponent(String(externalHubName)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new Kmehrmessage(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve a transaction set for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction set identifier.
   * @summary Get a transaction set (a collection of transactions) for a patient. This is mainly used for medication schemes.
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param ssin The SSIN of the patient
   * @param sv The SV part of the identifier of the transaction set. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction set. Obtained from the transaction list.
   * @param id The ID of the transaction set to retrieve
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   * @param externalHubId The ID of the hub (1990000035 for RSW, 1990000728 for Abrumet, 1990000134 for Cozo, 1990001916 for Vitalink, ...)
   * @param externalHubName The name of the hub, if applicable
   */
  getTransactionSetUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    ssin: string,
    sv: string,
    sl: string,
    id: string,
    hubPackageId?: string,
    breakTheGlassReason?: string,
    externalHubId?: string,
    externalHubName?: string
  ): Promise<Kmehrmessage> {
    let _body = null

    const _url =
      this.host +
      `/hub/ts/${encodeURIComponent(String(ssin))}/${encodeURIComponent(
        String(sv)
      )}/${encodeURIComponent(String(sl))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (id ? "&id=" + encodeURIComponent(String(id)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "") +
      (externalHubId ? "&externalHubId=" + encodeURIComponent(String(externalHubId)) : "") +
      (externalHubName ? "&externalHubName=" + encodeURIComponent(String(externalHubName)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new Kmehrmessage(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve a specific transaction for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction ID.
   * @summary Get a transaction (document, scan, ...) for a patient
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param ssin The SSIN of the patient
   * @param sv The SV part of the identifier of the transaction. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction. Obtained from the transaction list.
   * @param id The ID of the transaction to retrieve
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   * @param externalHubId The ID of the hub (1990000035 for RSW, 1990000728 for Abrumet, 1990000134 for Cozo, 1990001916 for Vitalink, ...)
   * @param externalHubName The name of the hub, if applicable
   */
  getTransactionUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    ssin: string,
    sv: string,
    sl: string,
    id: string,
    hubPackageId?: string,
    breakTheGlassReason?: string,
    externalHubId?: string,
    externalHubName?: string
  ): Promise<Kmehrmessage> {
    let _body = null

    const _url =
      this.host +
      `/hub/t/${encodeURIComponent(String(ssin))}/${encodeURIComponent(
        String(sv)
      )}/${encodeURIComponent(String(sl))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (id ? "&id=" + encodeURIComponent(String(id)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "") +
      (externalHubId ? "&externalHubId=" + encodeURIComponent(String(externalHubId)) : "") +
      (externalHubName ? "&externalHubName=" + encodeURIComponent(String(externalHubName)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => new Kmehrmessage(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to retrieve the list of transactions for a patient. It requires the healthcare provider's information, the patient's SSIN, and the hub package ID. The date range, author information, and transaction types can be provided to filter the results.
   * @summary Get the list of transactions (documents, scans, ...) for a patient
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param from The start date of the search for transactions in format YYYYMMDD
   * @param to The end date of the search for transactions in format YYYYMMDD
   * @param authorNihii The Nihii of the author of the transaction, optional
   * @param authorSsin The SSIN of the author of the transaction, optional
   * @param isGlobal Whether the transaction search is global (on all hubs through intrahub) or local (on the hub where the request is made)
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   * @param transactionTypes The list of transaction types to filter the results, such as &#x27;document&#x27;, &#x27;scan&#x27;, &#x27;message&#x27;, etc. If not provided, all transaction types are returned.
   */
  getTransactionsListUsingGET(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string,
    from?: number,
    to?: number,
    authorNihii?: string,
    authorSsin?: string,
    isGlobal?: boolean,
    breakTheGlassReason?: string,
    transactionTypes?: Array<string>
  ): Promise<Array<TransactionSummaryDto>> {
    let _body = null

    const _url =
      this.host +
      `/hub/list/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (from ? "&from=" + encodeURIComponent(String(from)) : "") +
      (to ? "&to=" + encodeURIComponent(String(to)) : "") +
      (authorNihii ? "&authorNihii=" + encodeURIComponent(String(authorNihii)) : "") +
      (authorSsin ? "&authorSsin=" + encodeURIComponent(String(authorSsin)) : "") +
      (isGlobal ? "&isGlobal=" + encodeURIComponent(String(isGlobal)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "") +
      (transactionTypes ? "&transactionTypes=" + encodeURIComponent(String(transactionTypes)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("GET", _url, headers, _body, this.fetchImpl)
      .then(doc => (doc.body as Array<JSON>).map(it => new TransactionSummaryDto(it)))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to manage access rights for another healthcare provider to access a patient's data. It requires the healthcare provider's information, the identifiers of the document and the rights that need to be set.
   * @summary Put an access right for a healthcare provider to access a patient's data
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param sv The SV part of the identifier of the transaction. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction. Obtained from the transaction list.
   * @param value The value of the transaction to manage, usually the ID of the transaction
   * @param accessRight The access right to set for the healthcare provider (allow, disallow)
   * @param accessNihii The Nihii of the healthcare provider to allow/disallow access, optional
   * @param accessSsin The SSIN of the healthcare provider to allow/disallow access, optional
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   */
  putAccessRightUsingPOST(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    sv: string,
    sl: string,
    value: string,
    accessRight: string,
    accessNihii?: string,
    accessSsin?: string,
    hubPackageId?: string
  ): Promise<PutAccessRightResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/access` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (sv ? "&sv=" + encodeURIComponent(String(sv)) : "") +
      (sl ? "&sl=" + encodeURIComponent(String(sl)) : "") +
      (value ? "&value=" + encodeURIComponent(String(value)) : "") +
      (accessRight ? "&accessRight=" + encodeURIComponent(String(accessRight)) : "") +
      (accessNihii ? "&accessNihii=" + encodeURIComponent(String(accessNihii)) : "") +
      (accessSsin ? "&accessSsin=" + encodeURIComponent(String(accessSsin)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new PutAccessRightResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows to create or update a patient in the hubs. It requires the healthcare provider's information and the patient's details.It allows a healthcare provider to register a patient in the hub system, which is necessary for managing patient data and consent.
   * @summary Create or update a patient in the hubs
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare party
   * @param hcpFirstName The first name of the healthcare party
   * @param hcpNihii The Nihii of the healthcare party
   * @param hcpSsin The SSIN of the healthcare party
   * @param hcpZip The ZIP code of the healthcare party
   * @param patientSsin The SSIN of the patient
   * @param firstName The first name of the patient
   * @param lastName The last name of the patient
   * @param gender The gender of the patient
   * @param dateOfBirth The date of birth of the patient in YYYYMMDD format
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. THis ID is usually different for acceptance and production environments.
   */
  putPatientUsingPOST(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    firstName: string,
    lastName: string,
    gender: string,
    dateOfBirth: number,
    hubPackageId?: string
  ): Promise<Patient> {
    let _body = null

    const _url =
      this.host +
      `/hub/patient/${encodeURIComponent(String(lastName))}/${encodeURIComponent(
        String(patientSsin)
      )}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (firstName ? "&firstName=" + encodeURIComponent(String(firstName)) : "") +
      (gender ? "&gender=" + encodeURIComponent(String(gender)) : "") +
      (dateOfBirth ? "&dateOfBirth=" + encodeURIComponent(String(dateOfBirth)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new Patient(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to put a transaction set for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction set message.
   * @summary Put a transaction set (a collection of transactions) for a patient. This is mainly used for medication schemes.
   * @param body The transaction set message in Kmehr format
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param hubId The ID of the hub (1990000035 for RSW, 1990000728 for Abrumet, 1990000134 for Cozo, 1990001916 for Vitalink, ...)
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param hubApplication Legacy, leave as null.
   */
  putTransactionSetUsingPOST(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    hubId: number,
    patientSsin: string,
    hubPackageId?: string,
    hubApplication?: string,
    body?: string
  ): Promise<PutTransactionSetResponse> {
    let _body = null
    _body = body

    const _url =
      this.host +
      `/hub/ts/${encodeURIComponent(String(hubId))}/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (hubApplication ? "&hubApplication=" + encodeURIComponent(String(hubApplication)) : "")
    let headers = this.headers
    headers = headers
      .filter(h => h.header !== "Content-Type")
      .concat(new XHR.Header("Content-Type", "application/xml"))
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new PutTransactionSetResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to put a transaction for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction message.
   * @summary Put a transaction (document, scan, ...) on the hubs for a patient
   * @param body The transaction message in Kmehr format
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param hubId The ID of the hub (1990000035 for RSW, 1990000728 for Abrumet, 1990000134 for Cozo, 1990001916 for Vitalink, ...)
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param hubApplication Legacy, leave as null.
   */
  putTransactionUsingPOST(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    hubId: number,
    patientSsin: string,
    hubPackageId?: string,
    hubApplication?: string,
    body?: string
  ): Promise<PutTransactionResponseDto> {
    let _body = null
    _body = body

    const _url =
      this.host +
      `/hub/t/${encodeURIComponent(String(hubId))}/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (hubApplication ? "&hubApplication=" + encodeURIComponent(String(hubApplication)) : "")
    let headers = this.headers
    headers = headers
      .filter(h => h.header !== "Content-Type")
      .concat(new XHR.Header("Content-Type", "application/xml"))
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new PutTransactionResponseDto(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to register a patient's consent in the hub system. It requires the healthcare provider's information and the patient's SSIN.It also requires some kind of proof of the patient's presence, such as an eid card number or isi card number for a child.
   * @summary Register a patient consent
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param patientEidCardNumber The eid card number of the patient, if available
   * @param patientIsiCardNumber The isi card number of the patient, if available
   */
  registerPatientConsentUsingPOST1(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string,
    patientEidCardNumber?: string,
    patientIsiCardNumber?: string
  ): Promise<PutPatientConsentResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/consent/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (patientEidCardNumber
        ? "&patientEidCardNumber=" + encodeURIComponent(String(patientEidCardNumber))
        : "") +
      (patientIsiCardNumber
        ? "&patientIsiCardNumber=" + encodeURIComponent(String(patientIsiCardNumber))
        : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new PutPatientConsentResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * A therapeutic link is a relationship between a healthcare provider and a patient that allows the healthcare provider to access the patient's data in the hub system. This endpoint allows a healthcare provider to register a therapeutic link for a patient. It requires the healthcare provider's information, the patient's SSIN, and some proof of presence such the eid card number, isi card number.
   * @summary Register a therapeutic link for a patient
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param patientEidCardNumber The eid card number of the patient, if available
   * @param patientIsiCardNumber The isi card number of the patient, if available
   * @param therLinkType The type of the therapeutic link
   * @param from The start date of the therapeutic link in format YYYYMMDD
   * @param to The end date of the therapeutic link in format YYYYMMDD
   */
  registerTherapeuticLinkUsingPOST(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string,
    patientEidCardNumber?: string,
    patientIsiCardNumber?: string,
    from?: number,
    to?: number,
    therLinkType?: string
  ): Promise<PutTherapeuticLinkResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/therlink/${encodeURIComponent(String(hcpNihii))}/${encodeURIComponent(
        String(patientSsin)
      )}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (patientEidCardNumber
        ? "&patientEidCardNumber=" + encodeURIComponent(String(patientEidCardNumber))
        : "") +
      (patientIsiCardNumber
        ? "&patientIsiCardNumber=" + encodeURIComponent(String(patientIsiCardNumber))
        : "") +
      (therLinkType ? "&therLinkType=" + encodeURIComponent(String(therLinkType)) : "") +
      (from ? "&from=" + encodeURIComponent(String(from)) : "") +
      (to ? "&to=" + encodeURIComponent(String(to)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new PutTherapeuticLinkResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to revoke access rights for another healthcare provider to access a patient's data. It requires the healthcare provider's information, the identifiers of the document and the identifier of the healthcare provider whose access needs to be revoked.
   * @summary Revoke an access right for a healthcare provider to access a patient's data
   * @param endpoint Endpoint URL of the hub (e.g., https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, etc.)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param sv The SV part of the identifier of the transaction. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction. Obtained from the transaction list.
   * @param value The value of the transaction to manage, usually the ID of the transaction
   * @param accessNihii The Nihii of the healthcare provider to allow/disallow access, optional
   * @param accessSsin The SSIN of the healthcare provider to allow/disallow access, optional
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   */
  revokeAccessRightUsingDELETE(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    sv: string,
    sl: string,
    value: string,
    accessNihii?: string,
    accessSsin?: string,
    hubPackageId?: string
  ): Promise<RevokeAccessRightResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/access` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (sv ? "&sv=" + encodeURIComponent(String(sv)) : "") +
      (sl ? "&sl=" + encodeURIComponent(String(sl)) : "") +
      (value ? "&value=" + encodeURIComponent(String(value)) : "") +
      (accessNihii ? "&accessNihii=" + encodeURIComponent(String(accessNihii)) : "") +
      (accessSsin ? "&accessSsin=" + encodeURIComponent(String(accessSsin)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => new RevokeAccessRightResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to revoke a patient's consent in the hub system. It requires the healthcare provider's information and the patient's SSIN.It also requires some kind of proof of the patient's presence, such as an eid card number or isi card number for a child.
   * @summary Revoke a patient's consent
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param patientEidCardNumber The eid card number of the patient, if available
   * @param patientIsiCardNumber The isi card number of the patient, if available
   */
  revokePatientConsentUsingDELETE(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string,
    patientEidCardNumber?: string,
    patientIsiCardNumber?: string
  ): Promise<RevokePatientConsentResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/consent/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (patientEidCardNumber
        ? "&patientEidCardNumber=" + encodeURIComponent(String(patientEidCardNumber))
        : "") +
      (patientIsiCardNumber
        ? "&patientIsiCardNumber=" + encodeURIComponent(String(patientIsiCardNumber))
        : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => new RevokePatientConsentResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to revoke a therapeutic link for a patient. It requires the healthcare provider's information, the patient's SSIN, and some proof of presence such the eid card number, isi card number.
   * @summary Revoke a therapeutic link for a patient
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param patientSsin The SSIN of the patient
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param patientEidCardNumber The eid card number of the patient, if available
   * @param patientIsiCardNumber The isi card number of the patient, if available
   * @param therLinkType The type of the therapeutic link to revoke
   */
  revokeTherapeuticLinkUsingDELETE(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    patientSsin: string,
    hubPackageId?: string,
    patientEidCardNumber?: string,
    patientIsiCardNumber?: string,
    therLinkType?: string
  ): Promise<RevokeTherapeuticLinkResponse> {
    let _body = null

    const _url =
      this.host +
      `/hub/therlink/${encodeURIComponent(String(hcpNihii))}/${encodeURIComponent(
        String(patientSsin)
      )}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (patientEidCardNumber
        ? "&patientEidCardNumber=" + encodeURIComponent(String(patientEidCardNumber))
        : "") +
      (patientIsiCardNumber
        ? "&patientIsiCardNumber=" + encodeURIComponent(String(patientIsiCardNumber))
        : "") +
      (therLinkType ? "&therLinkType=" + encodeURIComponent(String(therLinkType)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => new RevokeTherapeuticLinkResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   * This endpoint allows a healthcare provider to revoke a specific transaction for a patient. It requires the healthcare provider's information, the patient's SSIN, and the transaction ID.The actual deletion occurs if the healthcare provider has the right to do so, otherwise an error is triggered.
   * @summary Delete a transaction (document, scan, ...) for a patient
   * @param endpoint The endpoint URL of the hub (https://hub.reseausantewallon.be/HubServices/IntraHub/V3/IntraHub.asmx, https://hub.abrumet.be/hubservices/intrahub/v3/intrahub.asmx, https://services.cozo.be/IntrahubService/servicev3.asmx, https://vitalink.ehealth.fgov.be/vpmg/vitalink-gateway/IntraHubService, ...)
   * @param xFHCKeystoreId The keystore ID for the certificate of the healthcare provider
   * @param xFHCTokenId The token ID for the healthcare provider
   * @param xFHCPassPhrase The passphrase for the keystore
   * @param hcpLastName The last name of the healthcare provider
   * @param hcpFirstName The first name of the healthcare provider
   * @param hcpNihii The Nihii of the healthcare provider
   * @param hcpSsin The SSIN of the healthcare provider
   * @param hcpZip The ZIP code of the healthcare provider
   * @param ssin The SSIN of the patient
   * @param sv The SV part of the identifier of the transaction. Obtained from the transaction list.
   * @param sl The SL part of the identifier of the transaction. Obtained from the transaction list.
   * @param id The ID of the transaction to revoke
   * @param hubPackageId The ID of the software package used to access the hub, provided by the hub. This ID is usually different for acceptance and production environments.
   * @param breakTheGlassReason Allows a break the glass request (without a therapeutic link) by providing the reason for breaking the glass
   */
  revokeTransactionUsingDELETE(
    endpoint: string,
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpLastName: string,
    hcpFirstName: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpZip: string,
    ssin: string,
    sv: string,
    sl: string,
    id: string,
    hubPackageId?: string,
    breakTheGlassReason?: string
  ): Promise<string> {
    let _body = null

    const _url =
      this.host +
      `/hub/t/${encodeURIComponent(String(ssin))}/${encodeURIComponent(
        String(sv)
      )}/${encodeURIComponent(String(sl))}` +
      "?ts=" +
      new Date().getTime() +
      (endpoint ? "&endpoint=" + encodeURIComponent(String(endpoint)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpZip ? "&hcpZip=" + encodeURIComponent(String(hcpZip)) : "") +
      (id ? "&id=" + encodeURIComponent(String(id)) : "") +
      (hubPackageId ? "&hubPackageId=" + encodeURIComponent(String(hubPackageId)) : "") +
      (breakTheGlassReason
        ? "&breakTheGlassReason=" + encodeURIComponent(String(breakTheGlassReason))
        : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("DELETE", _url, headers, _body, this.fetchImpl)
      .then(doc => JSON.parse(JSON.stringify(doc.body)))
      .catch(err => this.handleError(err))
  }
}
