/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { XHR } from "./XHR"
import { MediprimaMdaResponse } from "../model/MediprimaMdaResponse"
import { TarificationMediprimaConsultationResult } from "../model/TarificationMediprimaConsultationResult"

export class fhcMediprimaApi {
  host: string
  headers: Array<XHR.Header>
  fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>

  constructor(
    host: string,
    headers: any,
    fetchImpl?: (input: RequestInfo, init?: RequestInit) => Promise<Response>
  ) {
    this.host = host
    this.headers = Object.keys(headers).map(k => new XHR.Header(k, headers[k]))
    this.fetchImpl = fetchImpl
  }

  setHeaders(h: Array<XHR.Header>) {
    this.headers = h
  }

  handleError(e: XHR.XHRError): never {
    throw e
  }

  /**
   *
   * @summary consultMediprimaTarification
   * @param body codes
   * @param patientSsin patientSsin
   * @param xFHCTokenId X-FHC-tokenId
   * @param xFHCKeystoreId X-FHC-keystoreId
   * @param xFHCPassPhrase X-FHC-passPhrase
   * @param hcpFirstName hcpFirstName
   * @param hcpLastName hcpLastName
   * @param hcpNihii hcpNihii
   * @param hcpSsin hcpSsin
   * @param date date
   * @param traineeSupervisorSsin traineeSupervisorSsin
   * @param traineeSupervisorNihii traineeSupervisorNihii
   * @param traineeSupervisorFirstName traineeSupervisorFirstName
   * @param traineeSupervisorLastName traineeSupervisorLastName
   */
  consultMediprimaTarificationUsingPOST(
    patientSsin: string,
    xFHCTokenId: string,
    xFHCKeystoreId: string,
    xFHCPassPhrase: string,
    hcpFirstName: string,
    hcpLastName: string,
    hcpNihii: string,
    hcpSsin: string,
    date: number,
    traineeSupervisorSsin?: string,
    traineeSupervisorNihii?: string,
    traineeSupervisorFirstName?: string,
    traineeSupervisorLastName?: string,
    body?: Array<string>
  ): Promise<TarificationMediprimaConsultationResult> {
    let _body = null
    _body = body

    const _url =
      this.host +
      `/mediprima/consultTarificationMediprima/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (hcpFirstName ? "&hcpFirstName=" + encodeURIComponent(String(hcpFirstName)) : "") +
      (hcpLastName ? "&hcpLastName=" + encodeURIComponent(String(hcpLastName)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (date ? "&date=" + encodeURIComponent(String(date)) : "") +
      (traineeSupervisorSsin
        ? "&traineeSupervisorSsin=" + encodeURIComponent(String(traineeSupervisorSsin))
        : "") +
      (traineeSupervisorNihii
        ? "&traineeSupervisorNihii=" + encodeURIComponent(String(traineeSupervisorNihii))
        : "") +
      (traineeSupervisorFirstName
        ? "&traineeSupervisorFirstName=" + encodeURIComponent(String(traineeSupervisorFirstName))
        : "") +
      (traineeSupervisorLastName
        ? "&traineeSupervisorLastName=" + encodeURIComponent(String(traineeSupervisorLastName))
        : "")
    let headers = this.headers
    headers = headers
      .filter(h => h.header !== "Content-Type")
      .concat(new XHR.Header("Content-Type", "application/json"))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new TarificationMediprimaConsultationResult(doc.body as JSON))
      .catch(err => this.handleError(err))
  }

  /**
   *
   * @summary consultMediprima
   * @param xFHCKeystoreId X-FHC-keystoreId
   * @param xFHCTokenId X-FHC-tokenId
   * @param xFHCPassPhrase X-FHC-passPhrase
   * @param hcpQuality hcpQuality
   * @param hcpNihii hcpNihii
   * @param hcpSsin hcpSsin
   * @param hcpName hcpName
   * @param patientSsin patientSsin
   * @param startDate startDate
   * @param endDate endDate
   * @param referenceDate referenceDate
   */
  consultMediprimaUsingPOST(
    xFHCKeystoreId: string,
    xFHCTokenId: string,
    xFHCPassPhrase: string,
    hcpQuality: string,
    hcpNihii: string,
    hcpSsin: string,
    hcpName: string,
    patientSsin: string,
    startDate?: number,
    endDate?: number,
    referenceDate?: number
  ): Promise<MediprimaMdaResponse> {
    let _body = null

    const _url =
      this.host +
      `/mediprima/consultMediprima/${encodeURIComponent(String(patientSsin))}` +
      "?ts=" +
      new Date().getTime() +
      (hcpQuality ? "&hcpQuality=" + encodeURIComponent(String(hcpQuality)) : "") +
      (hcpNihii ? "&hcpNihii=" + encodeURIComponent(String(hcpNihii)) : "") +
      (hcpSsin ? "&hcpSsin=" + encodeURIComponent(String(hcpSsin)) : "") +
      (hcpName ? "&hcpName=" + encodeURIComponent(String(hcpName)) : "") +
      (startDate ? "&startDate=" + encodeURIComponent(String(startDate)) : "") +
      (endDate ? "&endDate=" + encodeURIComponent(String(endDate)) : "") +
      (referenceDate ? "&referenceDate=" + encodeURIComponent(String(referenceDate)) : "")
    let headers = this.headers
    xFHCKeystoreId && (headers = headers.concat(new XHR.Header("X-FHC-keystoreId", xFHCKeystoreId)))
    xFHCTokenId && (headers = headers.concat(new XHR.Header("X-FHC-tokenId", xFHCTokenId)))
    xFHCPassPhrase && (headers = headers.concat(new XHR.Header("X-FHC-passPhrase", xFHCPassPhrase)))
    return XHR.sendCommand("POST", _url, headers, _body, this.fetchImpl)
      .then(doc => new MediprimaMdaResponse(doc.body as JSON))
      .catch(err => this.handleError(err))
  }
}
